environments:
  - name: production
    vpcCidrBlock: 10.0.0.0/16
    subnetCidrBlock: 10.0.0.0/24
  - name: staging
    vpcCidrBlock: 10.1.0.0/16
    subnetCidrBlock: 10.1.0.0/24


redshiftCluster:
  dbName: app
  nodeType: dc2.large
  numberOfNodes: 2
  securityGroup:
    whitelistedIps:
      - 5.6.7.8/32
      - 1.2.3.4/32
      - 9.10.11.12/32